name: testing-actions
on:
  push:
  pull_request:
    branches:
      - master
      - dev
jobs:
  run-tests:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      # Starting the mysql service
      - run: sudo /etc/init.d/mysql start
      # Create a user with access to the test database
      - run: mysql -u root -proot --execute="CREATE DATABASE IF NOT EXISTS crmintapp_test;"
      - run: mysql -u root -proot --execute="GRANT ALL PRIVILEGES ON crmintapp_test.* TO 'crmint'@'localhost' IDENTIFIED BY 'crmint'";
      # Checkout repository code
      - uses: actions/checkout@v2
      # Configure python
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      # Download App Engine SDK
      - uses: google-github-actions/setup-gcloud@v0
      # Update the App Engine environment
      - run: gcloud -q components update
      - run: gcloud -q components install app-engine-python
      # Setup the CRMint project
      - run: pip install -e cli/
      - run: crmint dev init --no-insight
      - run: crmint dev do requirements --no-insight
      - run: pip install -r backends/tests/requirements.txt
      # Run the tests
      - run: cd backends && python runtests.py $(gcloud info --format="value(installation.sdk_root)")
